-- ===========================================================================
-- EDA Question 3
-- Are there correlations between staff performance and customer satisfaction?
-- ==========================================================================

-- ----------------------------------------------------------------
-- Step 1: Calculate total rentals processed by each staff member
-- Purpose: Measure staff performance based on rental transactions.
-- ----------------------------------------------------------------

SELECT
    s.staff_id,
    CONCAT(s.first_name, ' ', s.last_name) AS staff_name,
    COUNT(r.rental_id) AS total_rentals
FROM staff s
JOIN rental r
    ON s.staff_id = r.staff_id
GROUP BY
    s.staff_id,
    s.first_name,
    s.last_name
ORDER BY total_rentals DESC;


-- ------------------------------------------------------------
-- Step 2: Calculate total revenue generated by each staff member
-- Purpose: Evaluate staff performance based on revenue.
-- ------------------------------------------------------------

SELECT
    s.staff_id,
    CONCAT(s.first_name, ' ', s.last_name) AS staff_name,
    ROUND(SUM(p.amount),2) AS total_revenue
FROM staff s
JOIN payment p
    ON s.staff_id = p.staff_id
GROUP BY
    s.staff_id,
    s.first_name,
    s.last_name
ORDER BY total_revenue DESC;


-- ------------------------------------------------------------
-- Step 3: Calculate average payment processed by each staff member
-- Purpose: Compare transaction values handled by staff members.
-- ------------------------------------------------------------

SELECT
    s.staff_id,
    CONCAT(s.first_name, ' ', s.last_name) AS staff_name,
    ROUND(AVG(p.amount),2) AS average_payment
FROM staff s
JOIN payment p
    ON s.staff_id = p.staff_id
GROUP BY
    s.staff_id,
    s.first_name,
    s.last_name
ORDER BY average_payment DESC;