-- ============================================================
-- EDA Question 8
-- How does the availability and knowledge of staff affect
-- customer ratings?
-- ============================================================

-- ------------------------------------------------------------
-- Step 1: Analyze staff workload
-- Purpose: Count rentals handled by each staff member.
-- ------------------------------------------------------------

SELECT
    s.staff_id,
    CONCAT(s.first_name, ' ', s.last_name) AS staff_name,
    COUNT(r.rental_id) AS total_rentals
FROM staff s
JOIN rental r
    ON s.staff_id = r.staff_id
GROUP BY
    s.staff_id,
    s.first_name,
    s.last_name
ORDER BY
    total_rentals DESC;
        
    
-- ------------------------------------------------------------
-- Step 2: Analyze revenue generated by staff
-- Purpose: Calculate total payments handled by each staff member.
-- ------------------------------------------------------------

SELECT
    s.staff_id,
    CONCAT(s.first_name, ' ', s.last_name) AS staff_name,
    ROUND(SUM(p.amount), 2) AS total_revenue
FROM staff s
JOIN payment p
    ON s.staff_id = p.staff_id
GROUP BY
    s.staff_id,
    s.first_name,
    s.last_name
ORDER BY
    total_revenue DESC;    